<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HP-VICTUS-144Hz" failures="1" tests="3" name="SeleniumPrjkt" time="6.58" errors="0" timestamp="2025-10-04T11:24:49 IST">
  <testcase classname="day46.ListenerClassDemo" name="testLogo" time="0.033"/>
  <testcase classname="day46.ListenerClassDemo" name="testUrl" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at day46.ListenerClassDemo.testUrl(ListenerClassDemo.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testUrl -->
  <testcase classname="day46.ListenerClassDemo" name="testTitle" time="0.0">
    <skipped/>
  </testcase> <!-- testTitle -->
</testsuite> <!-- SeleniumPrjkt -->
